id: I77DAEA77
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:13:46.444524+00:00
last_modified: 2022-12-14 18:13:46.444530+00:00
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-09-11T00:27:56.057Z'
  creationid: K.S.
  eft-text-id: UT22084-081-006
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_437-The_Practice_Manual_of_Noble_Tara_Kurukulla-v1
bases:
  0C53:
    source_metadata: null
    order: 1
    base_file: 0C53.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
